name: zz debos image build
run-name: ${{ inputs.board }} image build
on:
  workflow_call:
    inputs:
      board:
        description: name of target board
        required: true
        type: string
      kernel:
        description: kernel artifact name
        required: true
        type: string
      firmware:
        description: firmware artifact name
        required: true
        type: string
      suite:
        description: debian suite for image
        required: false
        type: string
        default: "bookworm"
    outputs:
      artifact:
        description: image artifact name
        value: ${{ jobs.build.outputs.artifact }}

env:
  artifact-name: debiant-${{ inputs.suite }}-${{ inputs.board }}

jobs:
  build:
    runs-on: [ self-hosted, linux, x64 ]
    outputs:
      artifact: ${{ env.artifact-name }}
    steps:
      - name: Clone repo
        id: clone
        uses: actions/checkout@v3

      - name: Install dependencies
        id: deps
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get -yq update && sudo apt-get -yq upgrade
          sudo apt-get -yq install git libglib2.0-dev libostree-dev \
            qemu-system-arm qemu-user-static debootstrap systemd-container

      - name: Set up golang
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'

      - name: install debos
        id: install-debos
        run: |
          source ${GITHUB_WORKSPACE}/scripts/ci_helpers.sh
          info "GOPATH=${GOPATH}"
          info "PATH=${PATH}"
          sudo go install -v github.com/go-debos/debos/cmd/debos@latest

      - name: Download kernel artifact
        id: get-kernel
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.kernel }}
          path: recipes/kernel/

      - name: Download u-boot artifact
        id: get-blorbs
        uses: actions/download-artifact@v3
        with:
          name: u-boot-${{ inputs.board }}
          path: recipes/u-boot/

      - name: Extract firmware .gz
        id: decompress-firmware
        working-directory: recipes/u-boot/
        run: gzip -d firmware-*.gz

      - name: List downloaded files
        id: list-artifacts
        run: |
          echo "Kernel artifact files:" && ls -lh recipes/kernel/ && echo ''
          echo "U-Boot artifact files:" && ls -lh recipes/u-boot/ && echo ''

      - name: Build ${{ matrix.boards.name }} Image
        id: do-build
        working-directory: recipes
        run: |
          source ${GITHUB_WORKSPACE}/scripts/ci_helpers.sh
          mkdir -p ../output
          info "debos=$(which debos)"
          sudo $(which debos) --disable-fakemachine --artifactdir ../output \
            -t suite:${{ inputs.suite }} \
            -t firmware:${{ inputs.firmware }} \
            recipe-${{ inputs.board }}.yaml

      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact-name }}
          path: output/*
          retention-days: 90
          if-no-files-found: error
