name: Quartz64 u-boot build

on:
  workflow_call:
    inputs:
      source-repo:
        required: true
        type: string
      source-ref:
        required: true
        type: string
      board-name:
        required: false
        default: "quartz64"
        type: string
      make-target:
        default: ""
        required: false
        type: string
    outputs:
      artifact-name:
        description: "output artifact name"
        value: ${{ jobs.build.outputs.artifact }}
      fw-blob:
        description: "firmware blob name"
        value: ${{ jobs.build.outputs.fw_blob }}

env:
  loader_bin: idblock.bin
  u_boot_bin: uboot.img
  fw_blob_name: firmware-${{ inputs.board-name }}.bin

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      artifact: u-boot-${{ inputs.board-name }}
      fw_blob: ${{ env.fw_blob_name }}.gz
    steps:
      - name: Install toolchain
        id: toolchain
        run: |
          sudo apt -y update
          sudo apt -y install build-essential crossbuild-essential-arm64 device-tree-compiler

      - name: Clone toolchain repository
        id: get-toolchain
        uses: actions/checkout@v3
        with:
          repository: neggles/sbci-toolchains
          ref: u-boot-quartz64
          path: toolchain

      - name: Clone rkbin repository
        id: get-rkbin
        uses: actions/checkout@v3
        with:
          repository: rockchip-linux/rkbin
          path: rkbin

      - name: Clone u-boot repository
        id: get-uboot
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.source-repo }}
          ref: ${{ inputs.source-ref }}
          path: u-boot

      - name: Download u-boot config
        id: get-config
        uses: actions/download-artifact@v3
        with:
          name: u-boot-config
          path: u-boot

      - name: Build u-boot
        id: build
        working-directory: u-boot
        run: |
          mv u-boot.config .config
          make oldconfig
          ./make.sh ${{ inputs.make-target }}

      - name: Assemble firmware blob
        id: blorb
        working-directory: u-boot
        run: |
          fallocate -l32m ${{ env.fw_blob_name }}
          dd if=${{ env.loader_bin }} of=${{ env.fw_blob_name }} conv=notrunc bs=32K seek=1
          dd if=${{ env.u_boot_bin }} of=${{ env.fw_blob_name }} conv=notrunc bs=32K seek=256
          gzip ${{ env.fw_blob_name }}

      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v3
        with:
          name: u-boot-${{ inputs.board-name }}
          path: |
            u-boot/${{ env.loader_bin }}
            u-boot/${{ env.u_boot_bin }}
            u-boot/${{ env.fw_blob_name }}.gz
            u-boot/*_spl_loader_*.bin
          retention-days: 30
          if-no-files-found: error
