name: Quartz64 Image Build
run-name: Quartz64 build via ${{ github.event_name }}

on:
  workflow_dispatch:
    inputs:
      build-kernel:
        description: Build kernel package
        required: true
        default:  true
        type: boolean
      build-u-boot:
        description: Build u-boot package
        required: true
        default:  true
        type: boolean

      kernel-ref:
        description: Kernel source ref
        required: true
        type: string
        default: "sbci-quartz64"
      u-boot-ref:
        description: u-boot source ref
        required: true
        type: string
        default: "sbci-quartz64"

defaults:
  run:
    shell: bash

env:
  kernel_repo: neggles/linux-quartz64
  kernel_config: rk356x.config

  u_boot_repo: neggles/u-boot-quartz64
  u_boot_config: rk3566-quartz64.config

  build_image: ${{ inputs.build-kernel && inputs.build-u-boot }}

jobs:
  upload-config:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone workflow repo
        uses: actions/checkout@v3

      - name: Copy config files
        run: |
          cp ./configs/kernel/${{ env.kernel_config }} ./kernel.config
          cp ./configs/u-boot/${{ env.u_boot_config }} ./u-boot.config

      - name: Upload kernel config
        uses: actions/upload-artifact@v3
        with:
          name: kernel_config
          path: kernel.config
          retention-days: 7
          if-no-files-found: error

      - name: Upload u-boot config
        uses: actions/upload-artifact@v3
        with:
          name: u_boot_config
          path: u-boot.config
          retention-days: 7
          if-no-files-found: error


  build-uboot:
    if: ${{ inputs.build-u-boot }}
    needs: upload-config
    uses: ./.github/workflows/quartz64-u-boot.yaml
    with:
      source-repo: ${{ env.u_boot_repo }}
      source-ref: ${{ inputs.u-boot-ref }}

  build-kernel:
    if: ${{ inputs.build-kernel }}
    needs: upload-config
    uses: ./.github/workflows/quartz64-kernel.yaml
    with:
      source-repo: ${{ env.kernel_repo }}
      source-ref: ${{ inputs.kernel-ref }}

  # build_image:
  #   if: ${{ env.build_image }}
  #   needs:
  #     - build-uboot
  #     - build-kernel
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       boards: [
  #           { name: "SOQuartz Blade",  }
  #         ]
