name: Quartz64 kernel build

on:
  workflow_call:
    inputs:
      source-repo:
        required: true
        type: string
      source-ref:
        required: true
        type: string
      artifact-name:
        required: false
        default: "kernel-debs"
        type: string
    outputs:
      kernelrelease:
        description: "uname -r"
        value: ${{ jobs.build.outputs.kernelrelease }}

jobs:
  build:
    runs-on: [ self-hosted, linux, x64 ]
    outputs:
      kernelrelease: ${{ steps.build.outputs.kernelrelease }}
    steps:
      - name: Install toolchain
        id: toolchain
        run: |
          sudo apt -y update
          sudo apt -y install build-essential crossbuild-essential-arm64 device-tree-compiler \
            quilt ccache flex bison libssl-dev dh-exec rsync libelf-dev bc fakeroot

      - name: Clone kernel repository
        id: get-linux
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.source-repo }}
          ref: ${{ inputs.source-ref }}
          path: linux

      - name: Download kernel config
        id: get-config
        uses: actions/download-artifact@v3
        with:
          name: kernel-config
          path: linux

      - name: Configure kernel
        id: configure
        working-directory: linux
        run: |
          mv kernel.config .config
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- olddefconfig

      - name: Build kernel
        id: build
        working-directory: linux
        run: |
          make -j$(nproc) ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- bindeb-pkg
          echo "kernelrelease=$(make -s kernelrelease)" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: |
            linux-*.deb
          retention-days: 30
          if-no-files-found: error
