name: Quartz64 Image Build
run-name: Quartz64 build via ${{ github.event_name }}
on:
  workflow_dispatch:
    inputs:
      build-kernel:
        description: Build kernel?
        required: false
        default:  true
        type: boolean
      kernel-repo:
        description: Kernel source repo
        required: false
        type: string
        default: neggles/linux-quartz64
      kernel-ref:
        description: Kernel repo ref
        required: true
        type: string
        default: "sbci-quartz64"

      build-u-boot:
        description: Build u-boot?
        required: false
        default:  true
        type: boolean
      u-boot-repo:
        description: U-Boot source repo
        required: false
        type: string
        default: neggles/u-boot-quartz64
      u-boot-ref:
        description: u-boot repo ref
        required: true
        type: string
        default: "sbci-quartz64"

defaults:
  run:
    shell: bash

env:
  kernel-config: rk356x.config
  u-boot-config: rk3566-quartz64.config
  build-image: ${{ inputs.build-kernel && inputs.build-u-boot }}

jobs:
  upload-config:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone workflow repo
        uses: actions/checkout@v3

      - name: Copy config files
        run: |
          cp ./configs/kernel/${{ env.kernel-config }} ./kernel.config
          cp ./configs/u-boot/${{ env.u-boot-config }} ./u-boot.config

      - name: Upload kernel config
        uses: actions/upload-artifact@v3
        with:
          name: kernel-config
          path: kernel.config
          retention-days: 7
          if-no-files-found: error

      - name: Upload u-boot config
        uses: actions/upload-artifact@v3
        with:
          name: u-boot-config
          path: u-boot.config
          retention-days: 7
          if-no-files-found: error


  build-uboot:
    if: ${{ inputs.build-u-boot }}
    needs: upload-config
    uses: ./.github/workflows/quartz64-u-boot.yaml
    with:
      source-repo: ${{ inputs.u-boot-repo }}
      source-ref: ${{ inputs.u-boot-ref }}

  build-kernel:
    if: ${{ inputs.build-kernel }}
    needs: upload-config
    uses: ./.github/workflows/quartz64-kernel.yaml
    with:
      source-repo: ${{ inputs.kernel-repo }}
      source-ref: ${{ inputs.kernel-ref }}

  # build-image:
  #   if: ${{ inputs.build-kernel and inputs.build-u-boot }}
  #   needs:
  #     - build-uboot
  #     - build-kernel
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       boards: [
  #           { name: "SOQuartz Blade",  }
  #         ]
