name: Quartz64 Image Build
run-name: Quartz64 image build (${{ github.event_name }})

on:
  workflow_dispatch:
    inputs:
      build-kernel:
        description: Build kernel package
        required: true
        default: true
        type: boolean
      build-u-boot:
        description: Build u-boot package
        required: true
        default: true
        type: boolean
      kernel-ref:
        description: Kernel source ref
        required: true
        type: string
        default: "sbci-quartz64"
      u-boot-ref:
        description: u-boot source ref
        required: true
        type: string
        default: "sbci-quartz64"

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-k${{ inputs.kernel-ref }}-b${{ inputs.u-boot-ref }}
  cancel-in-progress: true

env:
  kernel-config: rk356x.config
  u-boot-config: rk3566-quartz64.config
  build_image: ${{ inputs.build-kernel && inputs.build-u-boot }}

jobs:
  upload-config:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone workflow repo
        uses: actions/checkout@v3

      - name: Copy config files
        run: |
          cp ./configs/kernel/${{ env.kernel-config }} ./kernel.config
          cp ./configs/u-boot/${{ env.u-boot-config }} ./u-boot.config

      - name: Upload kernel config
        uses: actions/upload-artifact@v3
        with:
          name: kernel-config
          path: kernel.config
          retention-days: 7
          if-no-files-found: error

      - name: Upload u-boot config
        uses: actions/upload-artifact@v3
        with:
          name: u-boot-config
          path: u-boot.config
          retention-days: 7
          if-no-files-found: error

  build-uboot:
    if: inputs.build-u-boot
    needs: upload-config
    uses: ./.github/workflows/quartz64-u-boot.yaml
    strategy:
      fail-fast: false
      matrix:
        board-name: ["quartz64"]
        include:
          - board-name: quartz64
            make-target: ""
    with:
      source-repo: neggles/u-boot-quartz64
      source-ref: ${{ inputs.u-boot-ref }}
      board-name: ${{ matrix.board-name }}
      make-target: ${{ matrix.make-target }}

  build-kernel:
    if: inputs.build-kernel
    needs: upload-config
    uses: ./.github/workflows/quartz64-kernel.yaml
    with:
      source-repo: neggles/linux-quartz64
      source-ref: ${{ inputs.kernel-ref }}

  dump-output:
    runs-on: ubuntu-latest
    needs: [build-uboot, build-kernel]
    steps:
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: Dump needs context
        run: echo '${{ toJSON(needs) }}'

  # build_image:
  #   if: inputs.build-u-boot && inputs.build-kernel
  #   needs: [build-uboot, build-kernel]
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       boards: [
  #           { name: "SOQuartz Blade",  }
  #         ]
