name: Self-hosted runner image build

on:
  workflow_dispatch:
    inputs:
      push:
        description: "push to GHCR"
        type: boolean
        required: true
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:docker"
          file: "./Dockerfile."
          push: ${{ inputs.push }}
          tags: ghcr.io/neggles/sbci-actions-runner:latest,ghcr.io/neggles/sbci-actions-runner:${{ github.ref_name }}
          labels: org.opencontainers.image.description="sbci runner image"
          cache-from: type=gha
          cache-to: type=gha,mode=max
